name: Python package

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m ensurepip --upgrade && python -m pip install --upgrade setuptools
          pip install -r requirements-testing.txt
          pip install coveralls
          python setup.py install

      - name: Run tests
        run: |
          pytest --cov=nut2 tests/

      - name: Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        if: env.COVERALLS_REPO_TOKEN != ''
        run: |
          coveralls
